"""
app/models/organization.py
--------------------------
Organization ORM model.

Represents a tenant or organization within the ORQ platform.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Index, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Organization(Base):
    """Relational mapping for the ``organizations`` table.

    Columns
    -------
    id            : UUID primary key, generated by the database.
    name          : Required. Display name of the organization.
    slug          : Unique, indexed, required. URL-friendly identifier.
    description   : Optional text describing the organization.
    created_at    : Timestamp of row creation (UTC, set once by the DB).
    updated_at    : Timestamp of last modification (UTC, maintained by the DB).
    """

    __tablename__ = "organizations"
    __table_args__ = (
        Index("ix_organizations_slug", "slug"),
    )

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    slug: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
    )

    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
    )

    # ------------------------------------------------------------------
    # Timestamps — timezone-aware; set and maintained by the database.
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return f"<Organization {self.slug}>"
