"""
app/models/user.py
------------------
User ORM model — Phase 1 Step 2.

Represents an authenticated principal in the ORQ platform.
Authentication logic, password hashing, and CRUD are implemented
in later phases.  This module contains ONLY the database schema.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Index, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class User(Base):
    """Relational mapping for the ``users`` table.

    Columns
    -------
    id            : UUID primary key, generated by the database.
    email         : Unique, indexed, non-null. Used for authentication.
    username      : Unique, indexed, non-null. Human-readable handle.
    password_hash : Bcrypt/Argon2 hash stored by the auth service (Phase 2).
                    The plain-text password is never persisted.
    is_active     : Whether the account is enabled. Defaults to True.
    is_verified   : Whether email verification has been completed.
    is_superuser  : Whether the user has super-admin privileges.
    first_name    : Optional display name — given name.
    last_name     : Optional display name — family name.
    profile_image_url    : Optional URL to a profile image.
    created_at    : Timestamp of row creation (UTC, set once by the DB).
    updated_at    : Timestamp of last modification (UTC, maintained by the DB).
    """

    __tablename__ = "users"
    __table_args__ = (
        Index("ix_users_email", "email"),
        Index("ix_users_username", "username"),
    )
    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(254),       # RFC 5321 maximum email length
        unique=True,
        nullable=False,
    )

    username: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Security — ONLY the hash is stored; never the plain-text password.
    # ------------------------------------------------------------------
    password_hash: Mapped[str] = mapped_column(
        String(255),       # sufficient for bcrypt (60 chars) and Argon2id (~95+ chars)
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Status flags
    # ------------------------------------------------------------------
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default=func.true(),
    )

    is_verified: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )

    is_superuser: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
    )

    # ------------------------------------------------------------------
    # Optional profile fields
    # ------------------------------------------------------------------
    first_name: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        default=None,
    )

    last_name: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        default=None,
    )

    profile_image_url: Mapped[str | None] = mapped_column(
        String(2048),      # standard max URL length
        nullable=True,
        default=None,
    )

    # ------------------------------------------------------------------
    # Timestamps — timezone-aware; set and maintained by the database.
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
    DateTime(timezone=True),
    nullable=False,
    server_default=func.now(),
    onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return f"<User {self.email}>"
