"""add providers table

Revision ID: 5d6e7f8a9b0c
Revises: 4c5d6e7f8a9b
Create Date: 2026-08-02 13:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '5d6e7f8a9b0c'
down_revision: Union[str, None] = '4c5d6e7f8a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # -------------------------------------------------------------------------
    # Step 1 — Create provider_type_enum via idempotent raw DDL.
    # -------------------------------------------------------------------------
    op.execute(sa.text(
        "DO $$ BEGIN "
        "  CREATE TYPE provider_type_enum "
        "  AS ENUM ('openai', 'anthropic', 'gemini', 'groq', 'openrouter', 'azure_openai', 'ollama', 'lmstudio'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$;"
    ))

    # -------------------------------------------------------------------------
    # Step 2 — Reference enum type with create_type=False.
    # -------------------------------------------------------------------------
    provider_type_enum = ENUM(
        'openai', 'anthropic', 'gemini', 'groq', 'openrouter', 'azure_openai', 'ollama', 'lmstudio',
        name='provider_type_enum',
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', provider_type_enum, nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('api_key', sa.String(length=2048), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_organization_provider_name')
    )
    op.create_index(op.f('ix_providers_organization_id'), 'providers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_organization_id'), table_name='providers')
    op.drop_table('providers')
    
    # Drop the ENUM type
    op.execute(sa.text("DROP TYPE IF EXISTS provider_type_enum;"))
    # ### end Alembic commands ###
