"""add organization_quotas table

Revision ID: 3311c5eb7a21
Revises: 673f8316f4a6
Create Date: 2026-08-30 17:17:12.667664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3311c5eb7a21'
down_revision: Union[str, None] = '673f8316f4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_quotas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('request_limit', sa.BigInteger(), nullable=True),
    sa.Column('token_limit', sa.BigInteger(), nullable=True),
    sa.Column('requests_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('tokens_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_quotas_organization_id'), 'organization_quotas', ['organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_quotas_organization_id'), table_name='organization_quotas')
    op.drop_table('organization_quotas')
    # ### end Alembic commands ###
